<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Sanju" failures="1" tests="3" name="Runner.Ex15_CaptureFailedScenariosRunner" time="0.116" errors="0" timestamp="2024-12-31T08:54:20 IST" skipped="0">
  <testcase classname="Runner.Ex15_CaptureFailedScenariosRunner" name="runScenario" time="0.019"/>
  <system-out/>
  <testcase classname="Runner.Ex15_CaptureFailedScenariosRunner" name="runScenario" time="0.012"/>
  <system-out/>
  <testcase classname="Runner.Ex15_CaptureFailedScenariosRunner" name="runScenario" time="0.085">
    <failure message="expected [Hello] but found [Hi]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Hello] but found [Hi]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at Steps.LoginToAppWithoutTDSteps.user_should_be_on_home_page(LoginToAppWithoutTDSteps.java:39)
at âœ½.user should be on home page(file:///D:/10th%20Aug%202024/Workspace/10thAug24_CucumberProject/src/test/resources/FeatureFiles/Ex2_MultipleScenarioInSingleFeatureFile.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.Ex15_CaptureFailedScenariosRunner -->
